import { Value, ValueInput } from "../models";
import { VALUE_TYPE_ENUM } from "@rl/types";
import { logger } from "../common/helper/logger";

const checkIfValueExists = async (type: string, label: string) => {
  return Value.findOne({ type, label });
};

const createValue = async (value: ValueInput) => {
  const newValue = new Value(value);
  return newValue.save();
};

const labelsByType: Record<VALUE_TYPE_ENUM, string[]> = {
  [VALUE_TYPE_ENUM.GROWTH]: [
    "Growth-oriented",
    "Proactive",
    "Sales",
    "Data-driven",
    "Ambitious",
    "Goal-setting",
    "Self-improving",
    "Scaling mindset",
    "Opportunity-seeking",
    "Results-focused",
    "Continuous improvement",
    "Stretch goals",
    "Market-driven",
    "Performance-tracking",
    "Outcome-oriented",
    "Hungry to win",
    "Expansion-minded",
    "Revenue-focused",
    "Customer-growth",
    "Forward-thinking",
  ],
  [VALUE_TYPE_ENUM.LEARNING]: [
    "Open-minded",
    "Curious",
    "Lifelong learner",
    "Inquisitive",
    "Knowledge-sharing",
    "Reflective",
    "Experiment-driven",
    "Skill-building",
    "Coachable",
    "Adaptable learner",
    "Research-oriented",
    "Growth mindset",
    "Feedback-seeking",
    "Eager to learn",
    "Self-taught",
    "Cross-disciplinary",
    "Reading culture",
    "Continuous education",
    "Mentee mindset",
    "Knowledge-hungry",
  ],
  [VALUE_TYPE_ENUM.CHALLENGE]: [
    "Resilient",
    "Problem solver",
    "Determined",
    "Persistent",
    "Tenacious",
    "Risk-taker",
    "Bold",
    "Courageous",
    "Grit",
    "Solution-oriented",
    "Comfortable with ambiguity",
    "Crisis-ready",
    "High-pressure performer",
    "Adventurous",
    "Calculated risk-taker",
    "Obstacle-overcomer",
    "Stretch-seeking",
    "Hardworking",
    "Pioneering",
    "Unfazed by setbacks",
  ],
  [VALUE_TYPE_ENUM.INNOVATION]: [
    "Entrepreneurial",
    "Innovative",
    "Creative",
    "Inventive",
    "Disruptive",
    "Visionary",
    "Experimental",
    "Original thinker",
    "Design-thinking",
    "Future-focused",
    "Idea-driven",
    "Tech-savvy",
    "Trailblazing",
    "Out-of-the-box",
    "Prototyping mindset",
    "Bold ideas",
    "Transformative",
    "Imaginative",
    "Cutting-edge",
    "Reinventing norms",
  ],
  [VALUE_TYPE_ENUM.WORK]: [
    "Ownership mentality",
    "Independent",
    "Fast-paced",
    "Flexible",
    "Results-driven",
    "Hands-on",
    "Self-starter",
    "Reliable",
    "Hardworking",
    "Efficient",
    "Accountable",
    "Dedicated",
    "Pragmatic",
    "Versatile",
    "Disciplined",
    "Productive",
    "Resourceful",
    "Quality-focused",
    "Diligent",
    "Execution-focused",
  ],
  [VALUE_TYPE_ENUM.COMMUNICATE]: [
    "Clear communicator",
    "Active listener",
    "Transparent",
    "Articulate",
    "Persuasive",
    "Approachable",
    "Honest feedback",
    "Open dialogue",
    "Storytelling",
    "Concise",
    "Diplomatic",
    "Empathetic listener",
    "Direct",
    "Written communication",
    "Public speaking",
    "Cross-team communication",
    "Constructive feedback",
    "Responsive",
    "Inclusive language",
    "Negotiation skills",
  ],
  [VALUE_TYPE_ENUM.ORGANIZE]: [
    "Organised workflow",
    "Structured",
    "Detail-oriented",
    "Methodical",
    "Time management",
    "Prioritisation",
    "Planning-focused",
    "Process-driven",
    "Systematic",
    "Punctual",
    "Documentation-minded",
    "Deadline-driven",
    "Resource planning",
    "Project management",
    "Goal-tracking",
    "Workflow optimisation",
    "Thorough",
    "Consistent",
    "Coordinated",
    "Efficiency-focused",
  ],
  [VALUE_TYPE_ENUM.CONTRIBUTE]: [
    "Collaborative",
    "Team player",
    "Supportive",
    "Helpful",
    "Generous with time",
    "Cooperative",
    "Reliable teammate",
    "Knowledge-sharing",
    "Volunteering spirit",
    "Mutual support",
    "Goes the extra mile",
    "Dependable",
    "Initiative-taking",
    "Selfless",
    "Community-building",
    "Cross-functional",
    "Enabling others",
    "Contributing ideas",
    "Pitching in",
    "Value-adding",
  ],
  [VALUE_TYPE_ENUM.INTERPERSONAL]: [
    "Empathy",
    "Respect",
    "Psychological safety",
    "Humility",
    "Trustworthy",
    "Compassionate",
    "Emotional intelligence",
    "Patient",
    "Approachable",
    "Conflict resolution",
    "Relationship-building",
    "Kindness",
    "Genuine",
    "Considerate",
    "Open-hearted",
    "Self-aware",
    "Supportive presence",
    "Warm",
    "Tactful",
    "Understanding",
  ],
  [VALUE_TYPE_ENUM.ETHICAL]: [
    "Integrity",
    "Fairness",
    "Ethical leadership",
    "Honesty",
    "Accountability",
    "Transparency",
    "Trustworthiness",
    "Principled",
    "Responsible",
    "Compliance-minded",
    "Moral courage",
    "Consistency",
    "Confidentiality",
    "Conscientious",
    "Doing the right thing",
    "Anti-corruption",
    "Justice-oriented",
    "Reliable conduct",
    "Authentic",
    "Values-driven",
  ],
  [VALUE_TYPE_ENUM.SOCIAL]: [
    "Diversity-minded",
    "Community-oriented",
    "Inclusive",
    "Socially responsible",
    "Environmentally conscious",
    "Equity-focused",
    "Belonging-focused",
    "Culturally aware",
    "Volunteering",
    "Giving back",
    "Sustainability-minded",
    "Accessibility-focused",
    "Welcoming",
    "Civic-minded",
    "Cause-driven",
    "Open to all backgrounds",
    "Global mindset",
    "People-first",
    "Social impact",
    "Inclusive hiring",
  ],
  [VALUE_TYPE_ENUM.PERFORMANCE]: [
    "High-performance culture",
    "Team accountability",
    "Recognition culture",
    "Results-oriented",
    "Excellence-driven",
    "Goal-focused",
    "Continuous improvement",
    "Merit-based",
    "Metrics-driven",
    "Quality-obsessed",
    "Competitive",
    "Outcome-focused",
    "Productivity-focused",
    "Standards-driven",
    "Benchmarking",
    "Delivery-focused",
    "Efficiency-driven",
    "Customer-focused results",
    "Ownership of outcomes",
    "Raising the bar",
  ],
  [VALUE_TYPE_ENUM.DEVELOPMENT]: [
    "Mentorship",
    "Coaching culture",
    "Feedback culture",
    "Career development",
    "Skill-building",
    "Talent growth",
    "Learning & development",
    "Upskilling",
    "Stretch assignments",
    "Internal mobility",
    "Knowledge transfer",
    "Onboarding support",
    "Personal growth plans",
    "Continuous training",
    "Leadership pipeline",
    "Peer learning",
    "Growth conversations",
    "Performance coaching",
    "Succession planning",
    "Development opportunities",
  ],
  [VALUE_TYPE_ENUM.COLLABORATION]: [
    "Empowerment",
    "Servant leadership",
    "Cross-functional teamwork",
    "Shared ownership",
    "Trust-based teamwork",
    "Co-creation",
    "Open collaboration",
    "Team alignment",
    "Collective decision-making",
    "Partnership-driven",
    "Knowledge-sharing",
    "Unified goals",
    "Inclusive collaboration",
    "Transparency in teams",
    "Mutual accountability",
    "Pair working",
    "Consensus-building",
    "Team empowerment",
    "Collaborative problem-solving",
    "Stakeholder engagement",
  ],
  [VALUE_TYPE_ENUM.MOTIVATION]: [
    "Career progression",
    "Innovation",
    "Creativity",
    "Learning opportunities",
    "Leadership opportunities",
    "Recognition",
    "Impact-driven",
    "Challenging work",
    "Competitive pay",
    "Achievement-oriented",
    "Purpose-led",
    "Autonomy in work",
    "Mastery-seeking",
    "Reward-driven",
    "Ambition",
    "Goal achievement",
    "Variety of work",
    "Career advancement",
    "Visibility",
    "Drive to excel",
  ],
  [VALUE_TYPE_ENUM.MEANING]: [
    "Stability",
    "Social good",
    "Purpose-driven",
    "Mission-aligned",
    "Meaningful work",
    "Making a difference",
    "Long-term impact",
    "Values alignment",
    "Sense of belonging",
    "Legacy-building",
    "Contribution to society",
    "Customer impact",
    "Job security",
    "Work that matters",
    "Personal meaning",
    "Shared mission",
    "Cause-aligned",
    "Fulfilling vision",
    "Positive impact",
    "Higher purpose",
  ],
  [VALUE_TYPE_ENUM.FULFILMENT]: [
    "Autonomy",
    "Recognition",
    "Work-life balance",
    "Job satisfaction",
    "Sense of accomplishment",
    "Wellbeing-focused",
    "Flexibility",
    "Pride in work",
    "Personal fulfilment",
    "Happiness at work",
    "Healthy boundaries",
    "Meaningful relationships",
    "Sense of progress",
    "Appreciation",
    "Empowered to grow",
    "Mental health support",
    "Belonging",
    "Joy in work",
    "Balanced lifestyle",
    "Contentment",
  ],
};

export const valueSeeder = async () => {
  try {
    const values: ValueInput[] = Object.entries(labelsByType).flatMap(([type, labels]) =>
      labels.map((label) => ({ type: type as VALUE_TYPE_ENUM, label }))
    );

    await Promise.all(
      values.map(async (valueData) => {
        const existing = await checkIfValueExists(valueData.type, valueData.label);
        if (!existing) {
          await createValue(valueData);
        }
      })
    );

    logger.info("Value seeding completed.");
  } catch (error) {
    logger.error("Error seeding values", error);
  }
};
