export * from './user.authz';
export * from './event-registration.authz';
export * from './event.authz';
export * from './tenant.authz';
export * from './job.authz';
export * from './job-profile.authz';
export * from './cv.authz';
export * from './application.authz';
export * from './favourite.authz';
