export enum ONBOARDING_STEP_ENUMS {
  VALUES_STEP_1 = 'VALUES_STEP_1',
  VALUES_STEP_2 = 'VALUES_STEP_2',
  VALUES_STEP_3 = 'VALUES_STEP_3',
  VALUES_STEP_4 = 'VALUES_STEP_4',
  VALUES_STEP_5 = 'VALUES_STEP_5',
  CV_UPLOAD = 'CV_UPLOAD',
  JOB_TITLE = 'JOB_TITLE',
  INDUSTRY = 'INDUSTRY',
  EXPERIENCE_LEVEL = 'EXPERIENCE_LEVEL',
  WORK_MODE = 'WORK_MODE',
  LOCATION = 'LOCATION',
  NOTICE_BY_EMPLOYEE = 'NOTICE_BY_EMPLOYEE',
}
