import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import NextAuthProviders from '@/providers/next-auth-providers';
import { ReactQueryProvider } from '@/providers/react-query-provider';

const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <NextAuthProviders>
          <ReactQueryProvider>{children}</ReactQueryProvider>
        </NextAuthProviders>
      </body>
    </html>
  );
}
