import type { Metadata } from 'next';
import { Inter, Poppins } from 'next/font/google';
import './globals.css';
import NextAuthProviders from '@/providers/next-auth-providers';
import { ReactQueryProvider } from '@/providers/react-query-provider';
import { Toaster } from '@/components/ui/sonner';
import { AbilityProvider } from '@/authz/ability-provider';
import { AgentPageProvider } from '@/components/ai-chat/page-context';
const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${inter.variable} antialiased`}>
        <NextAuthProviders>
          <ReactQueryProvider>
            <AbilityProvider>
              {/* Wraps both the page and the chat widget mounted by each route-group layout. */}
              <AgentPageProvider>{children}</AgentPageProvider>
            </AbilityProvider>
          </ReactQueryProvider>
        </NextAuthProviders>
        <Toaster position="top-right" richColors />
      </body>
    </html>
  );
}
